// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingZ.Infrastructure.Persistence;

#nullable disable

namespace TrainingZ.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301201849_Notifications1")]
    partial class Notifications1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainingZ.Application.Common.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.CoachingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("CoachingDatas");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.DoneExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("DoneExercises");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.DoneSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoneExerciseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoneExerciseId", "SetIndex")
                        .IsUnique();

                    b.ToTable("DoneSets");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<double>("Intensity")
                        .HasColumnType("double precision");

                    b.Property<int>("IntensityType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sets")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingSectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSectionId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.InvitationData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasCoach")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserInfoId")
                        .IsUnique();

                    b.ToTable("InvitationDatas");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachingDataId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachingDataId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingUnitId");

                    b.ToTable("TrainingSections");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingUnits");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Injuries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Other")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SleepDiet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeAvaiable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TrainingUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingUnitId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("TrainingZ.Infrastructure.Auth.Entites.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("TrainingZ.Infrastructure.Auth.Entites.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.DoneExercise", b =>
                {
                    b.HasOne("TrainingZ.Domain.Entities.Workout", "Workout")
                        .WithMany("DoneExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.DoneSet", b =>
                {
                    b.HasOne("TrainingZ.Domain.Entities.DoneExercise", "DoneExercise")
                        .WithMany("DoneSets")
                        .HasForeignKey("DoneExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoneExercise");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("TrainingZ.Domain.Entities.TrainingSection", "TrainingSection")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSection");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.InvitationData", b =>
                {
                    b.HasOne("TrainingZ.Domain.Entities.UserInfo", "UserInfo")
                        .WithOne("InvitationData")
                        .HasForeignKey("TrainingZ.Domain.Entities.InvitationData", "UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingPlan", b =>
                {
                    b.HasOne("TrainingZ.Domain.Entities.CoachingData", "CoachingData")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("CoachingDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoachingData");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingSection", b =>
                {
                    b.HasOne("TrainingZ.Domain.Entities.TrainingUnit", "TrainingUnit")
                        .WithMany("TrainingSections")
                        .HasForeignKey("TrainingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingUnit");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingUnit", b =>
                {
                    b.HasOne("TrainingZ.Domain.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingUnits")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.Workout", b =>
                {
                    b.HasOne("TrainingZ.Domain.Entities.TrainingUnit", "TrainingUnit")
                        .WithMany("Workouts")
                        .HasForeignKey("TrainingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingUnit");
                });

            modelBuilder.Entity("TrainingZ.Infrastructure.Auth.Entites.RefreshToken", b =>
                {
                    b.HasOne("TrainingZ.Infrastructure.Auth.Entites.AppUser", "Owner")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.CoachingData", b =>
                {
                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.DoneExercise", b =>
                {
                    b.Navigation("DoneSets");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingPlan", b =>
                {
                    b.Navigation("TrainingUnits");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingSection", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.TrainingUnit", b =>
                {
                    b.Navigation("TrainingSections");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.UserInfo", b =>
                {
                    b.Navigation("InvitationData");
                });

            modelBuilder.Entity("TrainingZ.Domain.Entities.Workout", b =>
                {
                    b.Navigation("DoneExercises");
                });

            modelBuilder.Entity("TrainingZ.Infrastructure.Auth.Entites.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
